//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marys_Auto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int Employee_ID { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
        public string JobTitle { get; set; }
        public Nullable<decimal> HourlyWage { get; set; }
        public Nullable<int> Experience { get; set; }
    
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
