//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marys_Auto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public string Invoice_ID { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
        public string WorkDoneDescription { get; set; }
        public string Service_ID { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
