//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marys_Auto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public Vehicle()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int Vehicle_ID { get; set; }
        public string VehicleMake { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleTrim { get; set; }
        public string VehicleYear { get; set; }
        public string VIN { get; set; }
        public int Customer_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
